name = "portfolio"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "portfolio-db"
database_id = "2635797e-71bd-4eaf-9a3a-a26d480a9d6d"


